name: CI Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
      - main
    types:
      - opened
      - synchronize
  
  workflow_dispatch:

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    name: Build ${{ matrix.projectName }} ${{ matrix.buildTarget }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        projectName:
          - iptech-unitylibrary
          - iptech-unityservices
        buildTarget:
          - iOS
          - Android
        include:
          - projectName: iptech-unitylibrary
            projectPath: unity/iptech-unitylibrary
          - projectName: iptech-unityservices
            projectPath: unity/iptech-unityservices
          - buildTarget: iOS
            buildConfig: DebugiOS
          - buildTarget: Android
            buildConfig: DebugAndroid
            
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: LibraryBuild-${{ matrix.projectName }}-${{ matrix.buildTarget }}

      - uses: game-ci/unity-builder@v4
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.buildTarget }}
          buildMethod: IPTech.BuildTool.Builder.Build
          customParameters: -buildConfig ${{ matrix.buildConfig }}

  test:
    name: Test ${{ matrix.projectName }} ${{ matrix.buildTarget }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        projectName:
          - iptech-unitylibrary
          - iptech-unityservices
        buildTarget:
          - ios
          - android
        include:
          - projectName: iptech-unitylibrary
            projectPath: unity/iptech-unitylibrary
          - projectName: iptech-unityservices
            projectPath: unity/iptech-unityservices
          - buildTarget: iOS
            image: 'unityci/editor:ubuntu-6000.5.1f1-ios-3'
          - buildTarget: Android
            image: 'unityci/editor:ubuntu-6000.5.1f1-android-3'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: LibraryTest-${{ matrix.projectName }}-${{ matrix.buildTarget }}
      - uses: game-ci/unity-test-runner@v4
        id: tests
        with:
          testMode: editmode
          unityVersion: auto
          projectPath: ${{ matrix.projectPath }}
          customParameters: -buildTarget ${{ matrix.buildTarget }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customImage: ${{ matrix.image }}
          
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results for ${{ matrix.projectName }} ${{ matrix.buildTarget }}
          path: artifacts

  
